/**
 * Family notes and the "made it" log.
 *
 * Every entry is its own KV key under `note:<recipeId>:`, listed by prefix.
 * That is the whole reason this endpoint exists rather than a JSON blob through
 * /api/storage: two people writing a note on the same recipe at the same time
 * would each read the blob, add their line, and write it back — and whoever
 * finished second would erase the other. Separate keys cannot collide.
 *
 * The key carries the timestamp so a prefix listing comes back in the order
 * things were written; ISO strings sort correctly as text, which is the only
 * reason to spend the extra characters on one.
 *
 * The author is stamped here from the verified token and never read from the
 * request body, and the name that address is shown under comes from the roster
 * in shared/access.js. A client that could name its own author, or rename
 * itself into somebody else, could sign a note as anybody — which for the one
 * feature whose entire point is "who said this" would be worse than having no
 * attribution at all.
 *
 * GET ?recipe=<id>  everything said about one recipe
 * GET ?recent=<n>    the newest few from across the whole box, for the feed
 *
 * Requires the same RECIPES binding as /api/storage.
 */

import { identity, displayName } from "../../shared/access.js";

const json = (data, status = 200) =>
  new Response(JSON.stringify(data), {
    status,
    headers: { "Content-Type": "application/json", "Cache-Control": "no-store" },
  });

const NOTE_MAX = 2000;
/* How many the feed on the box page will show, and how far it will read to find
   them. Ten pages is ten thousand entries — far past anything this site will
   hold, and a bound so a runaway listing cannot spin. */
const FEED_MAX = 12;
const FEED_PAGES = 10;
/* A listing reads every entry, so this is the number of round trips one recipe
   can cost, not just how much is shown. */
const LIST_MAX = 200;

const noteKey = (recipe, at, rand) => `note:${recipe}:${at}-${rand}`;
/* Recipe ids are generated by the app, but they arrive here as a URL parameter
   and are concatenated into a KV key, so they are checked rather than trusted.
   A colon would let a crafted id read another recipe's notes. */
const okId = (v) => typeof v === "string" && /^[A-Za-z0-9_-]{1,64}$/.test(v);

/* Pulling the key apart again. A recipe id cannot contain a colon (okId sees to
   that), so the first colon after the prefix ends it; what follows is the ISO
   timestamp with a short random tail, and the tail is whatever comes after the
   last dash. The timestamp leads, so the remainder sorts chronologically as
   plain text — which is what makes a feed across every recipe possible without
   opening a single entry. */
function readKey(key) {
  const rest = key.slice("note:".length);
  const cut = rest.indexOf(":");
  if (cut < 0) return null;
  return { recipe: rest.slice(0, cut), stamp: rest.slice(cut + 1) };
}

/* Every note key on the site, newest last.
 *
 * A prefix listing comes back sorted by recipe, not by date, so the whole set
 * has to be seen before the newest few can be known. It is paged rather than
 * asked for in one go: a single call caps at 1000 keys and would silently
 * return the alphabetically-first thousand, which on a busy box would quietly
 * start hiding the most recent things — the one job this has. */
async function allNoteKeys(env) {
  const keys = [];
  let cursor;
  for (let page = 0; page < FEED_PAGES; page++) {
    const listed = await env.RECIPES.list({ prefix: "note:", limit: 1000, cursor });
    keys.push(...listed.keys.map((k) => k.name));
    if (listed.list_complete) break;
    cursor = listed.cursor;
    if (!cursor) break;
  }
  return keys;
}
export async function onRequest({ request, env }) {
  if (!env.RECIPES) {
    return json({ error: "KV namespace RECIPES is not bound to this project" }, 500);
  }

  const email = await identity(request);
  if (!email) {
    return json({ error: "Could not tell who is signed in, so there is nobody to sign this as" }, 403);
  }

  const url = new URL(request.url);

  try {
    if (request.method === "GET") {
      /* The whole site's activity, newest first, for the feed on the box page.
         Only the handful being shown are opened; the rest are sorted by their
         key alone. */
      const recent = url.searchParams.get("recent");
      if (recent !== null) {
        const want = Math.min(Math.max(parseInt(recent, 10) || 0, 1), FEED_MAX);
        const ordered = allNoteKeys(env)
          .then((keys) => keys
            .map((name) => ({ name, ...(readKey(name) || {}) }))
            .filter((k) => k.stamp)
            .sort((a, b) => (a.stamp < b.stamp ? 1 : a.stamp > b.stamp ? -1 : 0))
            .slice(0, want));

        const entries = [];
        for (const k of await ordered) {
          const raw = await env.RECIPES.get(k.name);
          if (!raw) continue;
          let e;
          try { e = JSON.parse(raw); } catch { continue; }
          entries.push({
            id: k.name,
            recipe: k.recipe,
            kind: e.kind === "made" ? "made" : "note",
            text: typeof e.text === "string" ? e.text : "",
            at: e.at || "",
            name: displayName(e.email || ""),
            mine: e.email === email,
          });
        }
        return json({ entries });
      }
      const recipe = url.searchParams.get("recipe");
      if (!okId(recipe)) return json({ error: "recipe required" }, 400);

      const listed = await env.RECIPES.list({ prefix: `note:${recipe}:`, limit: LIST_MAX });
      const entries = [];
      for (const k of listed.keys) {
        const raw = await env.RECIPES.get(k.name);
        if (!raw) continue;                       // deleted between listing and reading
        let e;
        try { e = JSON.parse(raw); } catch { continue; }
        entries.push({
          id: k.name,
          kind: e.kind === "made" ? "made" : "note",
          text: typeof e.text === "string" ? e.text : "",
          at: e.at || "",
          name: displayName(e.email || ""),
          mine: e.email === email,
        });
      }

      return json({ me: { name: displayName(email) }, entries, truncated: listed.list_complete === false });
    }

    if (request.method === "POST") {
      const body = await request.json();
      const recipe = body && body.recipe;
      if (!okId(recipe)) return json({ error: "recipe required" }, 400);

      const kind = body.kind === "made" ? "made" : "note";
      const text = String(body.text ?? "").trim().slice(0, NOTE_MAX);
      /* A note with nothing in it is a mistake; "made it" carries the fact by
         existing, so it is allowed to say nothing. */
      if (kind === "note" && !text) return json({ error: "a note needs something in it" }, 400);

      const at = new Date().toISOString();
      const rand = Math.random().toString(36).slice(2, 8);
      const key = noteKey(recipe, at, rand);
      await env.RECIPES.put(key, JSON.stringify({ kind, text, email, at }));

      return json({ entry: { id: key, kind, text, at, name: displayName(email), mine: true } }, 201);
    }

    if (request.method === "DELETE") {
      const id = url.searchParams.get("id");
      if (!id || !id.startsWith("note:")) return json({ error: "id required" }, 400);

      const raw = await env.RECIPES.get(id);
      if (!raw) return json({ error: "not found" }, 404);
      let e;
      try { e = JSON.parse(raw); } catch { e = null; }
      /* Only the person who wrote it. The check is here rather than in the app
         because the app is the thing being checked. */
      if (!e || e.email !== email) {
        return json({ error: "that isn't yours to remove" }, 403);
      }
      await env.RECIPES.delete(id);
      return json({ id, deleted: true });
    }

    return json({ error: "method not allowed" }, 405);
  } catch (err) {
    return json({ error: String(err && err.message ? err.message : err) }, 500);
  }
}
