/**
 * Family notes and the "made it" log.
 *
 * Every entry is its own KV key under `note:<recipeId>:`, listed by prefix.
 * That is the whole reason this endpoint exists rather than a JSON blob through
 * /api/storage: two people writing a note on the same recipe at the same time
 * would each read the blob, add their line, and write it back — and whoever
 * finished second would erase the other. Separate keys cannot collide.
 *
 * The key carries the timestamp so a prefix listing comes back in the order
 * things were written; ISO strings sort correctly as text, which is the only
 * reason to spend the extra characters on one.
 *
 * The author is stamped here from the verified token and never read from the
 * request body, and the name that address is shown under comes from the roster
 * in shared/access.js. A client that could name its own author, or rename
 * itself into somebody else, could sign a note as anybody — which for the one
 * feature whose entire point is "who said this" would be worse than having no
 * attribution at all.
 *
 * PHOTOS
 * A made-it can carry a picture. The small version rides inside the entry, so a
 * listing needs no extra round trips; the full-size one is a key of its own,
 * fetched only when somebody opens it. Keeping the big one out of the record is
 * the whole point: a feed of a dozen entries would otherwise drag a dozen
 * full-size photographs across the wire to show them at 90 pixels.
 *
 * REPLIES
 * A reply is a note that names the entry it answers in `parent`. Threads are
 * built by the app from that one field, so a reply costs exactly what a note
 * does: one write. Removing an entry that has replies under it would cut them
 * loose, so it becomes a placeholder instead — its place in the thread and
 * nothing else — and is cleared away once nothing hangs from it.
 *
 * GET ?recipe=<id>   everything said about one recipe
 * GET ?recent=<n>    the newest few from across the whole box, for the feed;
 *                    a reply also says whose note it answers (parentName)
 * GET ?photo=<noteId>  the full-size picture, as an image rather than as JSON
 * POST { love, on }  heart somebody else's entry, or stop — for everybody to see
 *
 * LOVES are kept in D1 (the MESSAGES binding), not beside the note in KV: see
 * shared/loves.js. Without that binding the notes still work, just unloved.
 *
 * Requires the same RECIPES binding as /api/storage.
 */

import { identity, displayName, personFor, personName, isPerson, isOwner } from "../../shared/access.js";
import { hasHate } from "../../shared/hate.js";
import { ensureLoves, setLove, lovesFor, dropLoves, NOTE } from "../../shared/loves.js";

const json = (data, status = 200) =>
  new Response(JSON.stringify(data), {
    status,
    headers: { "Content-Type": "application/json", "Cache-Control": "no-store" },
  });

const NOTE_MAX = 2000;
/* The thumbnail travels inside every listing, so its budget is per entry times
   however many are shown: a dozen of these in the feed is the number that
   matters, not one. The full-size cap is the same order as a recipe photo. */
const SHOT_MAX = 90_000;      // characters of data URL, so ~64KB of picture
const PHOTO_MAX = 2_500_000;  // ~1.8MB of picture, well under KV's 25MB value cap
/* How many the feed on the box page will show, and how far it will read to find
   them. Ten pages is ten thousand entries — far past anything this site will
   hold, and a bound so a runaway listing cannot spin. */
const FEED_MAX = 12;
const FEED_PAGES = 10;
/* A listing reads every entry, so this is the number of round trips one recipe
   can cost, not just how much is shown. */
const LIST_MAX = 200;

const noteKey = (recipe, at, rand) => `note:${recipe}:${at}-${rand}`;
/* The full-size picture for an entry, under its own prefix so that it is never
   caught by a `note:` listing — the feed reads every note key on the site, and
   sweeping up photographs there would be expensive and wrong. */
const photoKeyFor = (noteId) => (noteId.startsWith("note:") ? `shot:${noteId.slice("note:".length)}` : null);

/* An image the app made, or nothing.
 *
 * Checked rather than trusted, because this string is stored and later handed
 * back for a browser to render. The app always produces JPEG through a canvas,
 * so that is the only thing accepted: it keeps out data:text/html, and it keeps
 * out SVG, which is a document that can carry script rather than a picture.
 * The payload is checked for the base64 alphabet so that what comes back out is
 * the kind of thing that went in. */
const JPEG_URL = /^data:image\/jpeg;base64,[A-Za-z0-9+/]+=?=?$/;
const okImage = (v, cap) => typeof v === "string" && v.length <= cap && JPEG_URL.test(v);
/* Recipe ids are generated by the app, but they arrive here as a URL parameter
   and are concatenated into a KV key, so they are checked rather than trusted.
   A colon would let a crafted id read another recipe's notes. */
const okId = (v) => typeof v === "string" && /^[A-Za-z0-9_-]{1,64}$/.test(v);

/* Pulling the key apart again. A recipe id cannot contain a colon (okId sees to
   that), so the first colon after the prefix ends it; what follows is the ISO
   timestamp with a short random tail, and the tail is whatever comes after the
   last dash. The timestamp leads, so the remainder sorts chronologically as
   plain text — which is what makes a feed across every recipe possible without
   opening a single entry. */
function readKey(key) {
  const rest = key.slice("note:".length);
  const cut = rest.indexOf(":");
  if (cut < 0) return null;
  return { recipe: rest.slice(0, cut), stamp: rest.slice(cut + 1) };
}

/* One stored entry as the app sees it. A placeholder shows its place in the
   thread and nothing more: no words, no picture, and no name. */
const okParent = (v) => typeof v === "string" && v.startsWith("note:");
/* Whose profile picture goes beside an entry: the roster id, never the
   address. Somebody off the roster has no id but their address, so they get
   no picture rather than having that published (see /api/profile). */
const authorOf = (email) => {
  const person = personFor(email);
  return person && isPerson(person.id) ? person.id : null;
};
/* Who has hearted an entry, by name, with the reader marked as `you`. */
const lovers = (who, me) => who.map((id) => ({ id, name: personName(id), you: id === me }));

/* The hearts on these entries, or none. A database that is missing or having
   a bad moment costs the hearts, never the notes. */
async function lovesOn(env, keys) {
  if (!env.MESSAGES || !keys.length) return new Map();
  try {
    await ensureLoves(env.MESSAGES);
    return await lovesFor(env.MESSAGES, NOTE, keys);
  } catch {
    return new Map();
  }
}
async function forgetLoves(env, keys) {
  if (!env.MESSAGES || !keys.length) return;
  try {
    await ensureLoves(env.MESSAGES);
    await dropLoves(env.MESSAGES, NOTE, keys);
  } catch { /* an orphaned heart on nothing is shown to nobody */ }
}

/* `canRemove` is whether the reader may take this entry away: their own, or
   anybody's when the reader is the site's owner. A placeholder is nobody's.
   `canLove` is whether the reader may heart it: somebody on the roster, on
   somebody else's entry, where hearts are switched on at all. */
function present(id, e, email, owner = false, who = [], hearts = false) {
  const parent = okParent(e.parent) ? e.parent : null;
  if (e.deleted) {
    return { id, kind: "note", text: "", at: e.at || "", name: "", who: null, mine: false, canRemove: false, shot: null, hasPhoto: false, parent, deleted: true, loves: [], loved: false, canLove: false };
  }
  const me = authorOf(email);
  return {
    loves: lovers(who, me),
    loved: !!me && who.includes(me),
    canLove: hearts && !!me && e.email !== email && authorOf(e.email || "") !== me,
    id,
    kind: e.kind === "made" ? "made" : "note",
    text: typeof e.text === "string" ? e.text : "",
    at: e.at || "",
    name: displayName(e.email || ""),
    who: authorOf(e.email || ""),
    mine: e.email === email,
    canRemove: e.email === email || owner,
    shot: typeof e.shot === "string" ? e.shot : null,
    hasPhoto: e.hasPhoto === true,
    parent,
    deleted: false,
  };
}

/* Every entry on one recipe, by id, for working out who answers whom. */
async function threadOf(env, recipe) {
  const listed = await env.RECIPES.list({ prefix: `note:${recipe}:`, limit: LIST_MAX });
  const thread = new Map();
  for (const k of listed.keys) {
    const raw = await env.RECIPES.get(k.name);
    if (!raw) continue;
    try { thread.set(k.name, JSON.parse(raw)); } catch { /* skip it */ }
  }
  return thread;
}

/* Every note key on the site, newest last.
 *
 * A prefix listing comes back sorted by recipe, not by date, so the whole set
 * has to be seen before the newest few can be known. It is paged rather than
 * asked for in one go: a single call caps at 1000 keys and would silently
 * return the alphabetically-first thousand, which on a busy box would quietly
 * start hiding the most recent things — the one job this has. */
async function allNoteKeys(env) {
  const keys = [];
  let cursor;
  for (let page = 0; page < FEED_PAGES; page++) {
    const listed = await env.RECIPES.list({ prefix: "note:", limit: 1000, cursor });
    keys.push(...listed.keys.map((k) => k.name));
    if (listed.list_complete) break;
    cursor = listed.cursor;
    if (!cursor) break;
  }
  return keys;
}
export async function onRequest({ request, env }) {
  if (!env.RECIPES) {
    return json({ error: "KV namespace RECIPES is not bound to this project" }, 500);
  }

  const email = await identity(request);
  if (!email) {
    return json({ error: "Could not tell who is signed in, so there is nobody to sign this as" }, 403);
  }
  const owner = isOwner(email);

  const url = new URL(request.url);

  try {
    if (request.method === "GET") {
      /* One picture, as a picture. Sent as image bytes rather than as JSON
         carrying a data URL, so that the gallery can point an <img> straight at
         this address and get the browser's own lazy loading and caching for
         free, instead of the app fetching and holding a megabyte of base64.

         Cached hard and privately: a picture at this address never changes —
         a new one is a new entry — so a browser may keep it as long as it
         likes, while `private` keeps it out of any shared cache, because what
         it holds is only for the family that got past Access. */
      const photo = url.searchParams.get("photo");
      if (photo !== null) {
        const key = photoKeyFor(photo);
        if (!key) return json({ error: "photo id required" }, 400);
        const stored = await env.RECIPES.get(key);
        if (!stored) return json({ error: "not found" }, 404);
        const comma = stored.indexOf(",");
        if (comma < 0) return json({ error: "not a picture" }, 500);
        const binary = atob(stored.slice(comma + 1));
        const bytes = new Uint8Array(binary.length);
        for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
        return new Response(bytes, {
          headers: {
            "Content-Type": "image/jpeg",
            "Cache-Control": "private, max-age=31536000, immutable",
          },
        });
      }

      /* The whole site's activity, newest first, for the feed on the box page.
         Only the handful being shown are opened; the rest are sorted by their
         key alone. */
      const recent = url.searchParams.get("recent");
      if (recent !== null) {
        const want = Math.min(Math.max(parseInt(recent, 10) || 0, 1), FEED_MAX);
        const ordered = allNoteKeys(env)
          .then((keys) => keys
            .map((name) => ({ name, ...(readKey(name) || {}) }))
            .filter((k) => k.stamp)
            .sort((a, b) => (a.stamp < b.stamp ? 1 : a.stamp > b.stamp ? -1 : 0))
            .slice(0, want * 4));

        /* A few more are read than are wanted, because placeholders are
           skipped — a removed note is not news — and the feed should still
           come back full. */
        const entries = [];
        for (const k of await ordered) {
          if (entries.length === want) break;
          const raw = await env.RECIPES.get(k.name);
          if (!raw) continue;
          let e;
          try { e = JSON.parse(raw); } catch { continue; }
          if (e.deleted) continue;
          const shown = { ...present(k.name, e, email, owner), recipe: k.recipe };
          /* A reply in the feed says whose note it answers, so it reads as a
             reply and can take somebody to that note. One more read, and only
             for the replies among the handful shown. An empty name means the
             note it answered has since been removed. */
          if (shown.parent) {
            let answered = null;
            try { answered = JSON.parse((await env.RECIPES.get(shown.parent)) || "null"); } catch { answered = null; }
            shown.parentName = answered && !answered.deleted ? displayName(answered.email || "") : "";
          }
          entries.push(shown);
        }
        return json({ entries });
      }
      const recipe = url.searchParams.get("recipe");
      if (!okId(recipe)) return json({ error: "recipe required" }, 400);

      const listed = await env.RECIPES.list({ prefix: `note:${recipe}:`, limit: LIST_MAX });
      const stored = [];
      for (const k of listed.keys) {
        const raw = await env.RECIPES.get(k.name);
        if (!raw) continue;                       // deleted between listing and reading
        let e;
        try { e = JSON.parse(raw); } catch { continue; }
        stored.push([k.name, e]);
      }
      /* Every entry's hearts in one query, not one each. */
      const loves = await lovesOn(env, stored.map(([key]) => key));
      const entries = stored.map(([key, e]) => present(key, e, email, owner, loves.get(key) || [], !!env.MESSAGES));

      return json({ me: { name: displayName(email) }, entries, truncated: listed.list_complete === false });
    }

    if (request.method === "POST") {
      const body = await request.json();

      /* A heart on somebody else's entry, or taking it back. Stamped with the
         reader's roster id from the token, like an author; somebody off the
         roster has no name to show under a heart, so cannot give one. */
      if (body && body.love !== undefined) {
        if (!env.MESSAGES) return json({ error: "Loves aren't switched on for this site yet" }, 501);
        const id = String(body.love);
        if (!id.startsWith("note:")) return json({ error: "which note?" }, 400);
        const me = authorOf(email);
        if (!me) return json({ error: "Only the family can love a note" }, 403);
        let e = null;
        try { e = JSON.parse((await env.RECIPES.get(id)) || "null"); } catch { e = null; }
        if (!e || e.deleted) return json({ error: "that note has been removed" }, 404);
        if (e.email === email || authorOf(e.email || "") === me) return json({ error: "You can't love your own note" }, 400);
        await ensureLoves(env.MESSAGES);
        await setLove(env.MESSAGES, { kind: NOTE, target: id, person: me, on: body.on !== false });
        const who = (await lovesFor(env.MESSAGES, NOTE, [id])).get(id) || [];
        return json({ id, loves: lovers(who, me), loved: who.includes(me) });
      }

      const recipe = body && body.recipe;
      if (!okId(recipe)) return json({ error: "recipe required" }, 400);

      /* A reply names the entry it answers, which has to be on this same
         recipe and still there: a reply to nothing would float free of any
         thread. A reply is always a note, because "I made this" is news, not
         an answer to anyone. */
      let parent = null;
      if (body.parent != null) {
        parent = String(body.parent);
        if (!parent.startsWith(`note:${recipe}:`)) {
          return json({ error: "a reply has to answer something on the same recipe" }, 400);
        }
        let answered = null;
        try { answered = JSON.parse((await env.RECIPES.get(parent)) || "null"); } catch { answered = null; }
        if (!answered || answered.deleted) return json({ error: "what you're replying to has been removed" }, 404);
      }

      const kind = body.kind === "made" && !parent ? "made" : "note";
      const text = String(body.text ?? "").trim().slice(0, NOTE_MAX);

      /* A picture is optional, but a malformed one is refused rather than
         quietly dropped — somebody who waited for a photo to upload should be
         told it did not, not left to find out by its absence. */
      const wantsShot = body.shot != null || body.photo != null;
      const shot = okImage(body.shot, SHOT_MAX) ? body.shot : null;
      const photo = okImage(body.photo, PHOTO_MAX) ? body.photo : null;
      if (wantsShot && (!shot || !photo)) {
        return json({ error: "that photo couldn't be read — try a JPEG, or a smaller picture" }, 400);
      }

      /* Checked here as well as in the browser, for the same reason the author
         is stamped here: the browser is the thing being checked. */
      if (hasHate(text)) {
        return json({ error: "that note has language this site doesn't allow" }, 400);
      }

      /* A note with nothing in it is a mistake; "made it" carries the fact by
         existing, and so does a photograph. */
      if (kind === "note" && !text && !shot) return json({ error: "a note needs something in it" }, 400);

      const at = new Date().toISOString();
      const rand = Math.random().toString(36).slice(2, 8);
      const key = noteKey(recipe, at, rand);

      /* The picture first. If the second write fails there is an orphaned image
         nobody can reach, which costs a little space; the other order would
         show an entry promising a photograph that was never stored. */
      if (photo) await env.RECIPES.put(photoKeyFor(key), photo);
      await env.RECIPES.put(key, JSON.stringify({ kind, text, email, at, shot, hasPhoto: !!photo, ...(parent ? { parent } : {}) }));

      return json({
        entry: { id: key, kind, text, at, name: displayName(email), who: authorOf(email), mine: true, canRemove: true, shot, hasPhoto: !!photo, parent, deleted: false, loves: [], loved: false, canLove: false },
      }, 201);
    }

    if (request.method === "DELETE") {
      const id = url.searchParams.get("id");
      if (!id || !id.startsWith("note:")) return json({ error: "id required" }, 400);

      const raw = await env.RECIPES.get(id);
      if (!raw) return json({ error: "not found" }, 404);
      let e;
      try { e = JSON.parse(raw); } catch { e = null; }
      /* Only the person who wrote it, or the site's owner. The check is here
         rather than in the app because the app is the thing being checked. A
         placeholder is refused to everybody: it is what holds a thread together,
         and it goes on its own when its last reply does. */
      if (!e || e.deleted || (e.email !== email && !owner)) {
        return json({ error: "that isn't yours to remove" }, 403);
      }
      /* The picture goes either way. Left behind it would be unreachable but
         still counted against the space this site is allowed to use for free. */
      if (e.hasPhoto) {
        const shotKey = photoKeyFor(id);
        if (shotKey) await env.RECIPES.delete(shotKey);
      }

      /* An entry with replies can't simply vanish: they would lose what they
         were answering and the thread would come apart. It stays as a
         placeholder — its place and nothing else — until the last reply under
         it goes. Then it goes too, and so does any placeholder above it left
         with nothing hanging from it. The answer lists every id that is really
         gone, so the app can take out exactly those. */
      const where = readKey(id);
      const thread = where ? await threadOf(env, where.recipe) : new Map();
      const answered = (key) => [...thread].some(([k, v]) => k !== key && v && v.parent === key);

      if (answered(id)) {
        await env.RECIPES.put(id, JSON.stringify({ deleted: true, at: e.at || "", ...(e.parent ? { parent: e.parent } : {}) }));
        await forgetLoves(env, [id]);
        return json({ id, deleted: true, placeholder: id, removed: [] });
      }

      await env.RECIPES.delete(id);
      thread.delete(id);
      const removed = [id];
      let up = e.parent;
      for (let hops = 0; up && hops < LIST_MAX; hops++) {
        const above = thread.get(up);
        if (!above || !above.deleted || answered(up)) break;
        await env.RECIPES.delete(up);
        thread.delete(up);
        removed.push(up);
        up = above.parent;
      }
      await forgetLoves(env, removed);
      return json({ id, deleted: true, placeholder: null, removed });
    }

    return json({ error: "method not allowed" }, 405);
  } catch (err) {
    return json({ error: String(err && err.message ? err.message : err) }, 500);
  }
}
