/**
 * Family notes and the "made it" log.
 *
 * Every entry is its own KV key under `note:<recipeId>:`, listed by prefix.
 * That is the whole reason this endpoint exists rather than a JSON blob through
 * /api/storage: two people writing a note on the same recipe at the same time
 * would each read the blob, add their line, and write it back — and whoever
 * finished second would erase the other. Separate keys cannot collide.
 *
 * The key carries the timestamp so a prefix listing comes back in the order
 * things were written; ISO strings sort correctly as text, which is the only
 * reason to spend the extra characters on one.
 *
 * The author is stamped here from the verified token and never read from the
 * request body. A client that could name its own author could sign a note as
 * anybody, which for the one feature whose entire point is "who said this"
 * would be worse than having no attribution at all.
 *
 * Requires the same RECIPES binding as /api/storage.
 */

import { identity, nameFromEmail } from "../../shared/access.js";

const json = (data, status = 200) =>
  new Response(JSON.stringify(data), {
    status,
    headers: { "Content-Type": "application/json", "Cache-Control": "no-store" },
  });

const NOTE_MAX = 2000;
const NAME_MAX = 40;
/* A listing reads every entry, so this is the number of round trips one recipe
   can cost, not just how much is shown. */
const LIST_MAX = 200;

const noteKey = (recipe, at, rand) => `note:${recipe}:${at}-${rand}`;
const whoKey = (email) => `who:${email}`;

/* Recipe ids are generated by the app, but they arrive here as a URL parameter
   and are concatenated into a KV key, so they are checked rather than trusted.
   A colon would let a crafted id read another recipe's notes. */
const okId = (v) => typeof v === "string" && /^[A-Za-z0-9_-]{1,64}$/.test(v);

/* Names are resolved when the notes are read, not frozen into each entry, so
   changing your name fixes every note you have ever left. */
async function nameResolver(env) {
  const seen = new Map();
  return async (email) => {
    if (seen.has(email)) return seen.get(email);
    let name = null;
    try { name = await env.RECIPES.get(whoKey(email)); } catch { name = null; }
    const resolved = (name && name.trim()) || nameFromEmail(email);
    seen.set(email, resolved);
    return resolved;
  };
}

export async function onRequest({ request, env }) {
  if (!env.RECIPES) {
    return json({ error: "KV namespace RECIPES is not bound to this project" }, 500);
  }

  const email = await identity(request);
  if (!email) {
    return json({ error: "Could not tell who is signed in, so there is nobody to sign this as" }, 403);
  }

  const url = new URL(request.url);

  try {
    if (request.method === "GET") {
      const recipe = url.searchParams.get("recipe");
      if (!okId(recipe)) return json({ error: "recipe required" }, 400);

      const nameOf = await nameResolver(env);
      const listed = await env.RECIPES.list({ prefix: `note:${recipe}:`, limit: LIST_MAX });
      const entries = [];
      for (const k of listed.keys) {
        const raw = await env.RECIPES.get(k.name);
        if (!raw) continue;                       // deleted between listing and reading
        let e;
        try { e = JSON.parse(raw); } catch { continue; }
        entries.push({
          id: k.name,
          kind: e.kind === "made" ? "made" : "note",
          text: typeof e.text === "string" ? e.text : "",
          at: e.at || "",
          name: await nameOf(e.email || ""),
          mine: e.email === email,
        });
      }

      return json({ me: { name: await nameOf(email) }, entries, truncated: listed.list_complete === false });
    }

    if (request.method === "POST") {
      const body = await request.json();
      const recipe = body && body.recipe;
      if (!okId(recipe)) return json({ error: "recipe required" }, 400);

      const kind = body.kind === "made" ? "made" : "note";
      const text = String(body.text ?? "").trim().slice(0, NOTE_MAX);
      /* A note with nothing in it is a mistake; "made it" carries the fact by
         existing, so it is allowed to say nothing. */
      if (kind === "note" && !text) return json({ error: "a note needs something in it" }, 400);

      const at = new Date().toISOString();
      const rand = Math.random().toString(36).slice(2, 8);
      const key = noteKey(recipe, at, rand);
      await env.RECIPES.put(key, JSON.stringify({ kind, text, email, at }));

      const nameOf = await nameResolver(env);
      return json({ entry: { id: key, kind, text, at, name: await nameOf(email), mine: true } }, 201);
    }

    if (request.method === "PUT") {
      const body = await request.json();
      const name = String(body && body.name ? body.name : "").trim().slice(0, NAME_MAX);
      if (!name) return json({ error: "a name needs something in it" }, 400);
      await env.RECIPES.put(whoKey(email), name);
      return json({ me: { name } });
    }

    if (request.method === "DELETE") {
      const id = url.searchParams.get("id");
      if (!id || !id.startsWith("note:")) return json({ error: "id required" }, 400);

      const raw = await env.RECIPES.get(id);
      if (!raw) return json({ error: "not found" }, 404);
      let e;
      try { e = JSON.parse(raw); } catch { e = null; }
      /* Only the person who wrote it. The check is here rather than in the app
         because the app is the thing being checked. */
      if (!e || e.email !== email) {
        return json({ error: "that isn't yours to remove" }, 403);
      }
      await env.RECIPES.delete(id);
      return json({ id, deleted: true });
    }

    return json({ error: "method not allowed" }, 405);
  } catch (err) {
    return json({ error: String(err && err.message ? err.message : err) }, 500);
  }
}
